In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Asian_Monsoon_Flood_Risk_Index.csv')

In [3]:
df

,Region_ID,Monsoon_Intensity_Index,Topographic_Wetness_Index,River_Discharge_Rate_CMS,Deforestation_Rate_Pct,Urban_Impervious_Pct,Soil_Moisture_Anomaly,Flood_Probability,Flood_Target_Binary
0,Chao_Phraya_TH,74.362844,16.449025,1564.361885,27.566675,16.678039,0.658005,0.603003,0
1,Red_River_VN,57.222951,10.753842,205.219016,35.166157,34.865899,0.358294,0.411600,0
2,Mekong_Delta_VN,45.945754,16.092284,1109.951968,11.538884,35.505539,0.734650,0.541335,0
3,Red_River_VN,62.301348,11.934957,279.376150,14.406374,53.279847,0.873312,0.581188,0
4,Red_River_VN,83.526681,14.355790,4054.892388,76.178339,17.206297,0.428771,0.538685,0
...,...,...,...,...,...,...,...,...,...
14995,Mekong_Delta_VN,66.282486,13.611492,3808.442060,67.813361,20.254840,0.554243,0.527654,0
14996,Ayeyarwady_MM,57.236042,14.070887,7161.699076,51.589327,37.490033,0.240354,0.511313,0
14997,Ganges_Brahmaputra_BD,56.402909,14.860794,2657.215925,6.357460,36.137700,0.464279,0.499011,0
14998,Indus_Plain_PK,80.441324,11.436726,7679.380074,46.993677,33.619900,0.503754,0.463517,0
14999,Red_River_VN,77.352269,9.418767,734.604965,14.500434,88.817519,0.794447,0.665838,1

In [6]:
 pd.read_csv('Asian_Monsoon_Flood_Risk_Index.csv').info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Region_ID                  15000 non-null  str
 1   Monsoon_Intensity_Index    15000 non-null  float64
 2   Topographic_Wetness_Index  15000 non-null  float64
 3   River_Discharge_Rate_CMS   15000 non-null  float64
 4   Deforestation_Rate_Pct     15000 non-null  float64
 5   Urban_Impervious_Pct       15000 non-null  float64
 6   Soil_Moisture_Anomaly      15000 non-null  float64
 7   Flood_Probability          15000 non-null  float64
 8   Flood_Target_Binary        15000 non-null  int64
dtypes: float64(7), int64(1), str(1)
memory usage: 1.0 MB

In [7]:
 pd.read_csv('Asian_Monsoon_Flood_Risk_Index.csv', dtype={'Flood_Target_Binary': float})

,Region_ID,Monsoon_Intensity_Index,Topographic_Wetness_Index,River_Discharge_Rate_CMS,Deforestation_Rate_Pct,Urban_Impervious_Pct,Soil_Moisture_Anomaly,Flood_Probability,Flood_Target_Binary
0,Chao_Phraya_TH,74.362844,16.449025,1564.361885,27.566675,16.678039,0.658005,0.603003,0.0
1,Red_River_VN,57.222951,10.753842,205.219016,35.166157,34.865899,0.358294,0.411600,0.0
2,Mekong_Delta_VN,45.945754,16.092284,1109.951968,11.538884,35.505539,0.734650,0.541335,0.0
3,Red_River_VN,62.301348,11.934957,279.376150,14.406374,53.279847,0.873312,0.581188,0.0
4,Red_River_VN,83.526681,14.355790,4054.892388,76.178339,17.206297,0.428771,0.538685,0.0
...,...,...,...,...,...,...,...,...,...
14995,Mekong_Delta_VN,66.282486,13.611492,3808.442060,67.813361,20.254840,0.554243,0.527654,0.0
14996,Ayeyarwady_MM,57.236042,14.070887,7161.699076,51.589327,37.490033,0.240354,0.511313,0.0
14997,Ganges_Brahmaputra_BD,56.402909,14.860794,2657.215925,6.357460,36.137700,0.464279,0.499011,0.0
14998,Indus_Plain_PK,80.441324,11.436726,7679.380074,46.993677,33.619900,0.503754,0.463517,0.0
14999,Red_River_VN,77.352269,9.418767,734.604965,14.500434,88.817519,0.794447,0.665838,1.0

In [10]:
dfs = pd.read_csv('Asian_Monsoon_Flood_Risk_Index.csv', chunksize = 5000)

In [11]:
for chunks in dfs:
    print(chunks.shape)

(5000, 9)
(5000, 9)
(5000, 9)